course/urls.py
'''
=====================================================================
Copyright (C) 2021 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.2.

Languages: Python 3.8.5, Django 3.1.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    # path('institute', IndexTemplateView.as_view(), name="index"),
    path('institutes/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/create/', views.InstituteCreate.as_view(), name='institute-create'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),
    path('institute/<int:pk>/delete/', views.InstituteDelete.as_view(), name='institute-delete'),
    path('institute/<int:pk>/update', views.InstituteUpdate.as_view(), name='institute-update'),
]

urlpatterns += [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    path('course/create/', views.CourseCreate.as_view(), name='course-create'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('course/<int:pk>/update', views.CourseUpdate.as_view(), name='course-update'),
]

urlpatterns += [
    path('disciplines/', views.DisciplineListView.as_view(), name='discipline-list'),
    path('discipline/create/', views.DisciplineCreate.as_view(), name='disciplines-create'),
    path('discipline/<int:pk>/', views.DisciplineDetailView.as_view(), name='discipline-detail'),
    path('discipline/<int:pk>/delete/', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:pk>/update', views.DisciplineUpdate.as_view(), name='discipline-update'),
    path('discipline/<int:pk>/import/', views.ImportProfsDiscipline, name='discipline-profs-import'),
    path('discipline/<int:pk>/import2/', views.ImportClassroomsDiscipline, name='discipline-classrooms-import'),
]

urlpatterns += [
    # path('classrooms/',               views.ClassroomListView.as_view(), name=''),
    path('classroomsmy/', views.LoanedClassroomByUserListView.as_view(), name='classroom-mylist'),
    path('classroom/create/', views.ClassroomCreate.as_view(), name='classroom-create'),
    path('classroom/<int:pk1>/student/<int:pk2>/delete', views.ClassroomStudentDelete, name='classroom-student-delete'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('classroom/<int:pk>/update', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classroom/<int:pk>/import/', views.ImportStudentsClassroom, name='classroom-students-import'),
    path('classroom/<int:pk>/createNewStudent/', views.ClassroomStudentCreate, name='classroom-student-create'),
]

exam/urls.py
'''
=====================================================================
Copyright (C) 2021 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.2.

Languages: Python 3.8.5, Django 3.1.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/variation/', views.variationsExam, name='exam-variation'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

course/forms.py
from django import forms


class UpdateClassroomForm(forms.Form):
    # students = forms.ModelMultipleChoiceField(
    #    queryset=Classroom.objects.all(),
    #    help_text = _("Choose the classrooms"),
    #    label=_("Classrooms"))
    #def __init__(self, *args, **kwargs):
    #   super(UpdateClassroomForm, self).__init__(*args, **kwargs)
    pass

    def __init__(self, *args, **kwargs):
        super(UpdateClassroomForm, self).__init__(*args, **kwargs)
        try:
            # user = kwargs['initial']['question_who_created']
            # self.fields['topic'].queryset = Question.objects.filter(topic__course__discipline_profs=user)
            # self.fields['classrooms'].queryset = Classroom.objects.filter(discipline__discipline_profs=user)
            pass

        except:
            pass

course/views.py
'''
=====================================================================
Copyright (C) 2021 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.2.

Languages: Python 3.8.5, Django 3.1.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from tablib import Dataset

from account.models import User
from student.models import Student
from .models import Institute, Course, Discipline, Classroom
from .resources import StudentResource

@login_required
def ImportClassroomsDiscipline(request, pk):
    if request.user.get_group_permissions():
        perm = [p for p in request.user.get_group_permissions()]
        if not 'exam.change_exam' in perm:
            return HttpResponseRedirect("/")
    else:
        return HttpResponseRedirect("/")

    discipline = get_object_or_404(Discipline, pk=pk)

    if request.method == 'POST':
        dataset = Dataset()
        try:
            new_persons = request.FILES['myfileClassrooms']
            pass
        except:
            messages.error(request, _('ImportClassroomsDiscipline: choose a CSV following the model'))
            return render(request, 'exam/exam_errors.html', {})

        f = new_persons.read()#.decode('utf-8')
        f = f.decode('latin-1')

        for c in discipline.classrooms2.all():  # para cada classe da disciplina
            for s in c.students.all():  # remover os alunos existentes da classe
                c.students.remove(s)

        mystr4 = '/course/discipline/' + str(pk) + '/update'
        messages.info(request, _('Return to: ') + '<a href="' + mystr4 + '">link</a>', extra_tags='safe')
        messages.info(request, _('Discipline name') + ' >> ' + discipline.discipline_name, extra_tags='upper')

        contALL = 0
        contFault = 0
        studentsFault = ''
        for row in f.split('\n'):
            r = row.split(',')

            if len(r) < 2:
                r = row.split(';')

            if len(r) == 7:
                emailProf = r[6] = r[6].lstrip().rstrip()
                if not User.objects.filter(email=emailProf):  # verificar se professor não existe
                    if [i for u in discipline.courses.all() for i in u.institutes.all() if
                        i.institute_url[4:] == emailProf[emailProf.find('@') + 1:]]:
                        messages.error(request,
                                       _('ImportClassroomsDiscipline: The teacher is not registered in MCTest')+
                                       '  ' + emailProf)
                        return render(request, 'exam/exam_errors.html', {})

                for p in User.objects.filter(email=emailProf):  # registrar prof na disciplina, se não estiver
                    if p not in discipline.discipline_profs.all():
                        discipline.discipline_profs.add(p)

                ID = r[0].lstrip().rstrip()
                try:
                    ra_int = int(ID)
                except:
                    messages.error(request, _('ImportClassroomsDiscipline: ID must be digits only: ') + ID)
                    return render(request, 'exam/exam_errors.html', {})

                nome = r[1].lstrip().rstrip()
                if len(nome) > 50:
                    nome = nome[:50]
                emailSt = r[2].lstrip().rstrip()
                codigo = r[3].lstrip().rstrip()
                sala = r[4].lstrip().rstrip()
                modo = r[5].lstrip().rstrip()

                '''
                try:  # ATENCAO: NAO FAZ NADA SE ESTUDANTE JÁ EXISTIR, PARA NAO APAGAR DADOS ANTIGOS NO BD
                    s = Student.objects.get(student_ID=ID)
                    #s.delete()
                except:
                    #pass
                    s = Student.objects.create(
                        student_ID=ID,
                        student_name=nome,
                        student_email=emailSt,
                    )
                '''
                try:  # NOTE: update name and email if ID already exists
                    s_all = Student.objects.filter(student_ID=ID)
                    if len(s_all) > 1:
                        for s in s_all:  # delete student equals
                            if nome == s.student_name:
                                s.delete()

                    if not s_all:
                        Student.objects.create(
                            student_ID=ID,
                            student_name=nome,
                            student_email=emailSt,
                        )
                    else:  # if exists, update name and email
                        s = Student.objects.get(student_ID=ID)
                        s.student_name = nome
                        s.student_email = emailSt
                        s.save()
                    contALL += 1
                except:
                    contFault += 1
                    studentsFault += row + '\n'
                    pass

                # shows error message if exists more that one student with same ID
                s_all = Student.objects.filter(student_ID=ID)
                if len(s_all) > 1:
                    messages.error(request, _(
                        'ImportClassroomsDiscipline: exists more that one student with same ID:' + str(s_all)))
                    return render(request, 'exam/exam_errors.html', {})

                c = None
                for caux in Classroom.objects.filter(classroom_code=codigo):
                    if caux.discipline == discipline:
                        c = caux
                        break

                if not c:
                    c = Classroom.objects.create(
                        discipline=discipline,
                        classroom_code=codigo,
                        classroom_room=sala,
                        classroom_days='',
                        classroom_type=modo,
                    )

                for p in User.objects.filter(email=emailProf):  # add prof in CLASSROOM if there is not
                    if p not in c.classroom_profs.all():
                        c.classroom_profs.add(p)

                c.students.add(s)  # add student in CLASSROOM

        # Show messages
        countClasses = 0
        for c in discipline.classrooms2.all():
            countClasses += 1
            messages.info(request, _('Classroom') + ' >> ' + c.classroom_code, extra_tags='upper')
            for p in c.classroom_profs.all():
                mystr4 = 'PROF: ' + str(countClasses) + '; ' + p.first_name + '; ' + p.last_name + '; ' + p.email
                messages.info(request, mystr4)

            contS = 0
            for s in c.students.all():
                contS += 1
                mystr4 = str(contS) + ';    ' + s.student_ID + '; ' + s.student_name + '; ' + s.student_email
                messages.info(request, mystr4)

        messages.info(request, _('Discipline profs'), extra_tags='upper')
        contS = 0
        for p in discipline.discipline_profs.all():
            contS += 1
            mystr4 = str(contS) + ';    ' + p.first_name + '; ' + p.last_name + '; ' + p.email
            messages.info(request, mystr4)

        messages.info(request, _('TOTAL'), extra_tags='upper')
        messages.info(request, _('Registered;') + str(contALL))
        messages.info(request, _('Not registered;') + str(contFault))
        messages.info(request, str(studentsFault))

    return render(request, 'exam/exam_msg.html', {})
    # return HttpResponseRedirect("/course/discipline/" + str(pk) + "/update")


@login_required
def ImportProfsDiscipline(request, pk):
    if request.user.get_group_permissions():
        perm = [p for p in request.user.get_group_permissions()]
        if not 'exam.change_exam' in perm:
            return HttpResponseRedirect("/")
    else:
        return HttpResponseRedirect("/")
    discipline = get_object_or_404(Discipline, pk=pk)

    if request.method == 'POST':
        dataset = Dataset()
        try:
            new_persons = request.FILES['myfileProfs']
        except:
            messages.error(request, _('ImportProfsDiscipline: choose a CSV following the model!'))
            return render(request, 'exam/exam_errors.html', {})

        f = new_persons.read().decode('utf-8')

        mystr4 = '/course/discipline/' + str(pk) + '/update'
        messages.info(request, _('Return to: ') + '<a href="' + mystr4 + '">link</a>', extra_tags='safe')
        messages.info(request, _('Discipline profs') + ' >> ' + discipline.discipline_name, extra_tags='upper')

        count = 0
        for row in f.split('\n'):
            r = row.split(',')

            if len(r) < 2:
                r = row.split(';')

            if len(r) == 3:
                count += 1

course/templates/institute/institute_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "Delete Institute" %}</h5>

                <hr>

                {% if user.is_staff %}

                    <p class="card-text">
                        {% trans "Are you sure you want to delete the institute" %}: <code>{{ institute }}</code>?
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <hr/>
                        <div class="text-left">
                            <a href="{% url 'course:institute-list' %}" class="btn btn-outline-danger">
                                {% trans "Cancel" %}
                            </a>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-danger">{% trans "Delete" %}</button>
                        </div>
                    </form>

                {% endif %}

                <hr>
                {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
            </div>
        </div>
    </div>
{% endblock %}

course/templates/institute/institute_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Institute Detail" %}</h5>

                        <hr>

                        <h6 class="card-title"><strong>{% trans "Name" %}: </strong> {{ institute.institute_name }}
                        </h6>
                        <h6><strong>{% trans "Code" %}: </strong>{{ institute.institute_code }}</h6>
                        <h6><strong>{% trans "Logo" %}: </strong>{{ institute.institute_logo }}</h6>
                        <h6><strong>{% trans "URL" %}: </strong>{{ institute.institute_url }}</h6>
                        <h6><strong>{% trans "Exams generated" %}: </strong>{{ institute.institute_exams_generated }}
                        </h6>
                        <h6><strong>{% trans "Exams corrected" %}: </strong>{{ institute.institute_exams_corrected }}
                        </h6>
                        <h6>
                            <strong>{% trans "Questions corrected" %}: </strong>{{ institute.institute_questions_corrected }}
                        </h6>

                        <div style="margin-left:20px;margin-top:20px">
                            <hr>
                            {% csrf_token %}

                            {% if institute.courses2.all %}
                                <div class="card-body" style="background-color:#f3f3f3;">
                                    <h5 class="card-title">{% trans "Course List" %}</h5>
                                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">{% trans "Code" %}</th>
                                            <th scope="col">{% trans "Name" %}</th>
                                            <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for course in institute.courses2.all %}
                                            <tr>
                                                <td>
                                                    <a href="{% url 'course:course-detail'  pk=course.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ course.course_code }}
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'course:course-detail'  pk=course.pk %}"
                                                       class="btn btn-outline-info text-dark btn-sm">
                                                        {{ course }}</a>
                                                </td>

                                                <td class="text-right">
                                                    <!-- actions -->
                                                    {% if  user.is_staff %}
                                                        <a href="{% url 'course:course-update'  pk=course.pk %}"
                                                           class="btn btn-outline-primary btn-sm">
                                                            {% trans "Update" %}
                                                        </a>
                                                        <a href="{% url 'course:course-delete'  pk=course.pk %}"
                                                           class="btn btn-outline-danger btn-sm">
                                                            {% trans "Delete" %}
                                                        </a>
                                                    {% endif %}

                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}

                                <div class="text-center mt-5 mb-5 jumbotron">
                                    <h5>{% trans "There is no" %}
                                        <code> {% trans "Course" %} </code> {% trans "registered yet." %}
                                    </h5>
                                </div>

                            {% endif %}

                            {% if  user.is_staff %}
                                <hr/>
                                <div class="text-right">
                                    <a href="{% url 'course:course-create' %}" class="btn btn-primary">
                                        {% trans "Create a New Course" %}
                                    </a>
                                </div>
                            {% endif %}

                            <hr>
                            {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

course/templates/institute/institute_list.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Institute List" %}</h5>

                        {% if institute_list|length > 0 %}

                            <div class="card-body" style="background-color:#f3f3f3;">
                                <table id="example" class="table table-striped table-bordered" style="width:100%">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">{% trans "Code" %}</th>
                                        <th scope="col">{% trans "Name" %}</th>
                                        <th scope="col">{% trans "URL" %}</th>
                                        <th scope="col" class="text-right">{% trans "Actions" %}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for institute in institute_list %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'course:institute-detail' pk=institute.pk %}"
                                                   class="btn btn-outline-info text-dark btn-sm">
                                                    {{ institute.institute_code }}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'course:institute-detail' pk=institute.pk %}"
                                                   class="btn btn-outline-info text-dark btn-sm">
                                                    {{ institute }}
                                                </a>
                                            </td>
                                            </td>
                                            <td>
                                                <a href="http://{{ institute.institute_url }}"
                                                   class="btn btn-outline-warning text-dark btn-sm">
                                                    {{ institute.institute_url }}
                                                </a>
                                            </td>
                                            <td class="text-right">
                                                {% if  user.is_staff %}

                                                    <a href="{% url 'course:institute-update' pk=institute.pk %}"
                                                       class="btn btn-outline-primary btn-sm">
                                                        {% trans "Update" %}
                                                    </a>

                                                    <a href="{% url 'course:institute-delete' pk=institute.pk %}"
                                                       class="btn btn-outline-danger btn-sm">
                                                        {% trans "Delete" %}
                                                    </a>
                                                {% endif %}

                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>{% trans "There is no" %}
                                    <code> {% trans "Institute" %} </code> {% trans "registered yet." %}</h5>
                            </div>
                        {% endif %}

                        {% if  user.is_staff %}
                            <hr/>
                            <div class="text-right">
                                <a href="{% url 'course:institute-create' %}" class="btn btn-primary">
                                    {% trans "Create a New Institute" %}
                                </a>
                            </div>
                        {% endif %}

                        <hr>
                        {% trans "Only admin can update/create/delete institutes/courses/disciplines" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

course/templates/institute/institute_list.old.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}

    {% if user.is_staff %}

        {% if institute_list %}
            <h1>{% trans "Institute Update" %}</h1>
            <ul>

                {% for institute in institute_list %}
                    <li class="{% if institute.is_overdue %}text-danger{% endif %}">

                        <a href="/course/institute/{{ institute.pk }}/update">{{ institute.institute_code }}
                            - {{ institute.institute_name }}</a>
                    </li>
                {% endfor %}

            </ul>
        {% endif %}

        <form action="../institute/create/" method="">
            {% csrf_token %}
            <input type="submit" action="" value={% trans "Create a new Institute" %}/>
        </form>


    {% else %}

        {% if institute_list %}
            <h1>{% trans "Institute List" %}</h1>

            <ul>

                {% for institute in institute_list %}
                    <li class="{% if institutes.is_overdue %}text-danger{% endif %}">
                        <a href="/course/institute/{{ institute.pk }}">{{ institute.institute_code }}
                            - {{ institute.institute_name }}</a>
                    </li>
                {% endfor %}

            </ul>
        {% endif %}
    {% endif %}

{% endblock %}