course/urls.py
'''
=====================================================================
Copyright (C) 2021 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.2.

Languages: Python 3.8.5, Django 3.1.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    # path('institute', IndexTemplateView.as_view(), name="index"),
    path('institutes/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/create/', views.InstituteCreate.as_view(), name='institute-create'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),
    path('institute/<int:pk>/delete/', views.InstituteDelete.as_view(), name='institute-delete'),
    path('institute/<int:pk>/update', views.InstituteUpdate.as_view(), name='institute-update'),
]

urlpatterns += [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    path('course/create/', views.CourseCreate.as_view(), name='course-create'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('course/<int:pk>/update', views.CourseUpdate.as_view(), name='course-update'),
]

urlpatterns += [
    path('disciplines/', views.DisciplineListView.as_view(), name='discipline-list'),
    path('discipline/create/', views.DisciplineCreate.as_view(), name='disciplines-create'),
    path('discipline/<int:pk>/', views.DisciplineDetailView.as_view(), name='discipline-detail'),
    path('discipline/<int:pk>/delete/', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:pk>/update', views.DisciplineUpdate.as_view(), name='discipline-update'),
    path('discipline/<int:pk>/import/', views.ImportProfsDiscipline, name='discipline-profs-import'),
    path('discipline/<int:pk>/import2/', views.ImportClassroomsDiscipline, name='discipline-classrooms-import'),
]

urlpatterns += [
    # path('classrooms/',               views.ClassroomListView.as_view(), name=''),
    path('classroomsmy/', views.LoanedClassroomByUserListView.as_view(), name='classroom-mylist'),
    path('classroom/create/', views.ClassroomCreate.as_view(), name='classroom-create'),
    path('classroom/<int:pk1>/student/<int:pk2>/delete', views.ClassroomStudentDelete, name='classroom-student-delete'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('classroom/<int:pk>/update', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classroom/<int:pk>/import/', views.ImportStudentsClassroom, name='classroom-students-import'),
    path('classroom/<int:pk>/createNewStudent/', views.ClassroomStudentCreate, name='classroom-student-create'),
]

exam/urls.py
'''
=====================================================================
Copyright (C) 2021 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of MCTest 5.2.

Languages: Python 3.8.5, Django 3.1.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br
in any publication about it.

MCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

MCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/variation/', views.variationsExam, name='exam-variation'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
]

main/urls.py
from account import admin

"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('readme', views.readme, name='readme'),
    path('license', views.license, name='license'),
    path('contributors', views.contributors, name='contributors'),
    path('According', views.According, name='According'),
    path('users', views.users, name='users'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from account.forms import UserCreateForm
from django.urls import reverse_lazy
from account.models import User
from course.models import Institute, Course, Classroom, Discipline
from topic.models import Topic, Question, Answer
from exam.models import Exam
from student.models import Student

# Create your views here.


class SignUp(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

######################################
from django.contrib.sessions.models import Session
from django.utils import timezone

def According(request):
    return render(request, 'According.html', {})

def contributors(request):
    return render(request, 'contributors.html', {})

def users(request):
    return render(request, 'users.html', {})


def readme(request):
    return render(request, 'readme.html', {})


def license(request):
    return render(request, 'license.html', {})


def index(request):
    users = User.objects.order_by('-last_login')[:10]  # all list 10 last users-login

    # all users logged now
    # Session.objects.all().delete()
    sessions = Session.objects.filter(expire_date__gte=timezone.now())
    uid_list = []
    for session in sessions:
        data = session.get_decoded()
        uid_list.append(data.get('_auth_user_id', None))
    users_now = User.objects.filter(id__in=uid_list)

    num_institutes = Institute.objects.all().count()
    num_courses = Course.objects.all().count()
    num_disciplines = Discipline.objects.all().count()
    num_classrooms = Classroom.objects.all().count()
    num_exams = Exam.objects.all().count()
    num_users = User.objects.all().count()
    num_students = Student.objects.all().count()

    num_questions = Question.objects.all().count()
    num_topics = Topic.objects.all().count()
    num_QM = Question.objects.filter(question_type='QM').count()
    num_QT = Question.objects.filter(question_type='QT').count()
    num_Parametric = Question.objects.filter(question_parametric='yes').count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'index.html',
                  context={'num_institutes': num_institutes,
                           'num_courses': num_courses,
                           'num_disciplines': num_disciplines,
                           'num_classrooms': num_classrooms,
                           'num_questions': num_questions,
                           'num_topics': num_topics,
                           'num_QM': num_QM,
                           'num_QT': num_QT,
                           'num_Parametric': num_Parametric,
                           'num_exams': num_exams,
                           'num_users': num_users,
                           'num_students': num_students,
                           'users_now': users_now,
                           'users': users,
                           'num_visits': num_visits})

main/templates/According.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "According" %}</h5>

                <hr>
                <p>
                    {% trans "MCTest (available for free on GitHub) was deployed on the UFABC server:" %}<a href="http://mctest.ufabc.edu.br"> mctest.ufabc.edu.br</a>.
                </p>
                <p>
                    {% trans "At UFABC, MCTest is a collaborative service for the automatic generation and correction of training activities (such as Exercise Lists) and assessment activities (such as Evidence Examples)." %}
                </p>
                <p>
                    {% trans "This service is available free of charge to all professors at the UFABC." %}
                </p>
                <p>
                    {% trans "To use MCTest, the teacher must register on the platform and be enrolled in a discipline by its coordinator." %}
                </p>
                <p>
                    {% trans "All intellectual material (classes, videos, questions, etc.) made available on this site is protected by the copyright of its respective authors and, ultimately, is the property of UFABC." %}
                    {% trans "The authors who have the material available on the website agree to release its use without restrictions on the part of the institution's professors to whom they are linked only within the scope of the disciplines and courses of this institution. In addition, when I sign up for this service at this institution, I ACCEPT that:" %}
                </p>
                <ol>
                    <li>
                        {% trans "I can use for free all available questions already registered in the discipline in my exams;" %}
                    </li>
                    <li>
                        {% trans "I cannot publish questions created by other teachers in any other medium, such as books and articles;" %}
                    </li>
                    <li>
                        {% trans "All new questions that I create can be reused in tests prepared by other teachers of the same subject, without prior notice;" %}
                    </li>
                    <li>
                        {% trans "I can change other teachers' questions only if there is an error. However, without changing the authorship of the issue." %}
                    </li>
                </ol>

                <hr>

            </div>
        </div>
    </div>
{% endblock %}

main/templates/base_generic.html
{# base_generic.html it's the skeleton model #}
{% load static %}

<!DOCTYPE html>
<html lang="pt">

<head>
    {% load i18n %}
    <!-- Add additional CSS in static file -->
    {% load static %}

    <meta charset="utf-8">

    <!-- Title -->
    {% block title %}<title>MCTest</title>{% endblock %}

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'webMCTest.png' %}" type="image/png">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    {% block styles %}{% endblock %}

    <style>
        .carousel-caption {
            position: relative;
            left: 0;
            top: 0;
        }
    </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main:index' %}">
        <img src="{% static 'webMCTest.png' %}" height="45px">
    </a>
    <button class="navbar-toggler" type="button"
            data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:institute-list' %}">{% trans "All institutes" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:course-list' %}">{% trans "All courses" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:discipline-list' %}">{% trans "All disciplines" %}</a>
            </li>

            {% if user.is_authenticated and user.groups.all.0.name == 'professor' %}
                <li class="nav-item">
                    <a class="nav-link" href="/topic/topics">{% trans "All topics" %}</a>
                </li>

                {% if user.groups.all.0.name == 'professor' %}
                    <li class="nav-item">
                        <a class="nav-link" href="/topic/questions">{% trans "All questions" %}</a>
                    </li>
                {% endif %}

                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/exam/exams/">{% trans "All exams" %}</a>
                    </li>
                    <p>
                {% endif %}
            {% endif %}

        </ul>
        <ul class="navbar-nav float-right">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ user.username }}:</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/topic/myquestions/">{% trans "Questions" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/course/classroomsmy/">{% trans "Classrooms" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/exam/myexams/">{% trans "Exams" %}</a>
                </li>
                <p>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">{% trans "Admin" %}</a>
                        </li>
                    {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">{% trans "Logout" %}</a>
                </li>

            {% else %}
                <li><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">{% trans "Login" %}</a></li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="/signup">{% trans "Sign up" %}</a>
            </li>

        </ul>

    </div>
</nav>

<!-- Contend of site -->
{% block content %}{% endblock %}


{% block scripts %}{% endblock %}

<!-- For scrolls in tables -->
<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.6.0/css/buttons.bootstrap4.min.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.colVis.min.js"></script>

<hr>

<!-- table example -->
<script>
    $(document).ready(function () {
        var table = $('#example').DataTable({
            dom: "Bfrtip",
            scrollY: "550px",
            scrollX: true,
            paging: false,
            //bInfo: false,
            buttons: [
                {
                    extend: 'copy',
                    text: '{% trans 'copy' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    text: '{% trans 'csv' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    text: '{% trans 'excel' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    text: '{% trans 'pdf' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    text: '{% trans 'print' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },

                {
                    extend: 'colvis',
                    text: '{% trans 'column visibility' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
            ]
        });

        table.buttons().container()
            .appendTo('#example_wrapper .col-md-6:eq(0)');
    });

</script>

<!-- table example0 - show classrooms in disciplines detail -->
<script>
    $(document).ready(function () {
        var table = $('#example0').DataTable({
            dom: "Bfrtip",
            scrollY: "550px",
            scrollX: true,
            paging: false,
            //bInfo: false,
            buttons: [
                {
                    extend: 'copy',
                    text: '{% trans 'copy' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    text: '{% trans 'csv' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    text: '{% trans 'excel' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    text: '{% trans 'pdf' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    text: '{% trans 'print' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                //{
                //    extend: 'colvis',
                //    text: '{% trans 'column visibility' %}',
                //    exportOptions: {
                //        columns: ':visible'
                //    }
                //},
            ]
        });

        table.buttons().container()
            .appendTo('#example0_wrapper .col-md-6:eq(0)');
    });
</script>

<!-- table example1 - show exam update -->
<script>
    $('body').on('change', '#mass_select_all', function () {
        var rows, checked;
        rows = $('#example1').find('tbody tr');
        checked = $(this).prop('checked');
        $.each(rows, function () {
            var checkbox = $($(this).find('td').eq(0)).find('input').prop('checked', checked);
        });
    });
    /* Create an array with the values of all the checkboxes in a column */
    $.fn.dataTable.ext.order['dom-checkbox'] = function (settings, col) {
        return this.api().column(col, {order: 'index'}).nodes().map(function (td, i) {
            return $('input', td).prop('checked') ? '0' : '1';
        });
    }
    $(document).ready(function () {
        var table = $('#example1').DataTable({
            "columnDefs": [{
                "targets": [0],
                "orderDataType": 'dom-checkbox',
            }],
            dom: "Bfrtip",
            scrollY: "550px",
            scrollX: true,
            paging: false,
            bInfo: true,
            buttons: [
                {
                    extend: 'copy',
                    text: '{% trans 'copy' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    text: '{% trans 'csv' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    text: '{% trans 'excel' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    text: '{% trans 'pdf' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    text: '{% trans 'print' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },

                {
                    extend: 'colvis',
                    text: '{% trans 'column visibility' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
            ]
        });

        table.buttons().container()
            .appendTo('#example_wrapper .col-md-6:eq(0)');

        $(':checkbox').on('change', function (e) {
            var row = $(this).closest('tr');
            var hmc = row.find(':checkbox:checked').length;
            var kluj = parseInt(hmc);
            row.find('td.counter').text(kluj);
            table.row(row).invalidate('dom');
        });
    });
</script>

<style>
    table.dataTable {
        border-collapse: collapse !important;
    }
</style>


<ul>
    <font size="2" color="black">
        <a href="https://www.gnu.org/licenses/agpl-3.0.html"><img
                src="{% static 'agplv3.png' %}"></a>
        <a href="{% url 'main:license' %}">Copyright © 2021</a> {% trans "by" %}
        <a href="https://sites.google.com/site/fzampirolli/">Francisco de Assis Zampirolli</a>
        {% trans "from" %} <a
            href="http://www.ufabc.edu.br">UFABC</a> {% trans "and" %}
        <a href="{% url 'main:contributors' %}">{% trans "individual contributors" %}</a>;
        <a href="{% url 'main:users' %}">{% trans "Who use" %}</a>;
        <a href="http://github.com/fzampirolli/mctest">{% trans "Download" %}</a>;
        <a href="https://docs.google.com/document/d/17OKZDVb13KUBwo-IM9OW6ASFSPUMMrTFf8HWZ8dum-o/edit?usp=sharing"> {% trans "Manual" %};
            <a href="{% url 'main:readme' %}"> {% trans "README" %}.</a><br>
            {% trans "Grant" %}: <a href="http://www.ufabc.edu.br">UFABC</a>;
            <a href="https://bv.fapesp.br/pt/auxilios/28430/modelagem-de-objetos-usando-morfologia-matematica-e-grafos-de-vizinhanca/">
                #2009/14430–1</a> {% trans "and" %}
            <a href="https://bv.fapesp.br/pt/auxilios/105047/um-sistema-universal-para-geracao-e-correcao-automatica-de-questoes-parametrizadas/">
                #2018/23561-1</a> - <a href="http://fapesp.br">FAPESP</a>

    </font>
</ul>

</body>

</html>

main/templates/contributors.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "Contributors" %}</h5>

                <hr>

                <ol>
                    <li>
                        {% trans "Thanks to many contributors who provided interesting information and are co-authors of the publications presented at" %}
                        <a href="vision.ufabc.edu.br">vision.ufabc.edu.br</a>.
                    </li>

                    <li>
                        {% trans "We also thank the contributors who helped codify MCTest, unknown in web discussion forums" %}.
                    </li>

                    <li>
                        {% trans "I think the big difference with MCTest is the parameterized issue, which may need custom Python functions to make writing easier. In this regard, I also thank" %}
                        (<a href="{% static 'Utils.py' %}">Utils.py</a>):
                    </li>
                    <ul>
                        <li>
                            Jorge Tomioka -  UFABC
                        </li>
                    </ul>
                </ol>

                <hr>

                <p>{% trans "I hope this list grows more and more" %} ...</p>

                {% trans "Please email" %} <a
                    href="mailto:fzampirolli@ufabc.edu.edu">fzampirolli@ufabc.edu.edu</a> {% trans "if I forgot anyone" %}.

            </div>
        </div>
    </div>
{% endblock %}

main/templates/signup.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">{% trans "Sign up" %}</h5>

                        <hr>
                        <h2>{% trans "Sign up" %}</h2>
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    <div class="group_{{ field.auto_id }}">
                                        {{ field.label_tag }}<br>
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text }}</small>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                </div>
                                </p>
                            {% endfor %}
                        <div class="text-right">
                            <a href="{% url 'main:According' %}" class="btn btn-outline-danger">
                                {% trans "According" %}</a>
                            <button type="submit" class="btn btn-primary">{% trans "Sign up" %}</button>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}